# Main display
output eDP-1 scale 1.2

#
# Framework 16 keyboard
#
bindsym F1 exec pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym F2 exec pactl set-sink-volume @DEFAULT_SINK@ -5% && pactl get-sink-volume @DEFAULT_SINK@ | head -n 1| awk '{print substr($5, 1, length($5)-1)}' > $WOBSOCK
bindsym F3 exec pactl set-sink-volume @DEFAULT_SINK@ +5% && pactl get-sink-volume @DEFAULT_SINK@ | head -n 1| awk '{print substr($5, 1, length($5)-1)}' > $WOBSOCK
bindsym F4 exec playerctl previous
bindsym F5 exec playerctl play-pause
bindsym F6 exec playerctl next

bindsym F7 exec brightnessctl set 5%- | sed -En 's/.*\(([0-9]+)%\).*/\1/p' > $WOBSOCK
bindsym F8 exec brightnessctl set 5%+ | sed -En 's/.*\(([0-9]+)%\).*/\1/p' > $WOBSOCK

# F9 is reduce mic volume
bindsym F9 exec pactl set-source-volume @DEFAULT_SOURCE@ -5% && pactl get-source-volume @DEFAULT_SOURCE@ | head -n 1| awk '{print substr($5, 1, length($5)-1)}' > $WOBSOCK
# F10 is increase mic volume
bindsym F10 exec pactl set-source-volume @DEFAULT_SOURCE@ +5% && pactl get-source-volume @DEFAULT_SOURCE@ | head -n 1| awk '{print substr($5, 1, length($5)-1)}' > $WOBSOCK
