#!/bin/sh

##################################################################
# Usage
##################################################################

Usage() {
  echo "usage: ./install [config]"
  echo
  echo "config:"
  echo "    brew (OS X only)"
  echo "    vim"
  echo "    zsh"
  echo "    powerline"
  echo "    tmux"
  echo "    link"
  echo
}

##################################################################
# Brew
##################################################################

InstallBrew() {
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

##################################################################
# Vim
##################################################################

InstallMacVim() {
  brew install vim --with-lua
}

InstallLinuxVim() {
  sudo apt-get remove --purge vim vim-runtime vim-gnome vim-tiny vim-common vim-gui-common
  sudo apt-get install liblua5.1-dev luajit libluajit-5.1 python-dev ruby-dev libperl-dev mercurial libncurses5-dev libgnome2-dev libgnomeui-dev libgtk2.0-dev libatk1.0-dev libbonoboui2-dev libcairo2-dev libx11-dev libxpm-dev libxt-dev
  sudo mkdir /usr/include/lua5.1/include
  sudo ln -s /usr/include/luajit-2.0 /usr/include/lua5.1/include

  mkdir -p ~/tmp && cd ~/tmp || exit
  git clone https://github.com/vim/vim.git
  cd vim/src || exit
  make distclean
  ./configure --with-features=huge \
              --enable-rubyinterp \
              --enable-largefile \
              --disable-netbeans \
              --enable-pythoninterp \
              --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu \
              --enable-perlinterp \
              --enable-luainterp \
              --with-luajit \
              --enable-gui=auto \
              --enable-fail-if-missing \
              --with-lua-prefix=/usr/include/lua5.1 \
              --enable-cscope
  make

  sudo make install

  cd .. || exit
  sudo mkdir /usr/share/vim
  sudo mkdir /usr/share/vim/vim74
  sudo cp -fr runtime/* /usr/share/vim/vim74/
}


##################################################################
# Zsh
##################################################################

SetZsh() {
  zsh --version
  chsh -s "$(which zsh)"
}

MacZsh() {
  brew install zsh
  SetZsh
}

LinuxZsh() {
  sudo apt-get install zsh
  SetZsh
}

InstallZsh() {
  sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
}


##################################################################
# Powerline
##################################################################

CheckPyVersion() {
  python --version
  pip --version
}

InstallPythonMac() {
  brew install python
  CheckPyVersion
}

InstallPythonLinux() {
  sudo apt-get -y install python
  sudo apt-get -y install python-pip
  CheckPyVersion
}

InstallPowerline() {
  pip install --user powerline-status
  mkdir -p ~/tmp && cd ~/tmp || exit
  git clone git@github.com:powerline/fonts.git
  fonts/install.sh

  echo "*************************************************************"
  echo "Please set font to 'Meslo LG S for Powerline'"
  echo "*************************************************************"

  echo "Adding path to .zshrc"
}


##################################################################
# Tmux
##################################################################

InstallTmuxMac() {
  brew install tmux
}

InstallTmuxLinux() {
  sudo apt-get install tmux
}


##################################################################
# Helper functions
##################################################################

MacOrLinux() {
  if [ "$2" = "--mac" ]; then
    $3
  elif [ "$2" = "--linux" ]; then
    $4
  fi
}

LinkFiles() {
    # Link files
    ln -sf "$CONFIG/.zshrc" "$HOME/.zshrc"
    ln -sf "$CONFIG/.sqliterc" "$HOME/.sqliterc"
    ln -sf "$CONFIG/.tmux.conf" "$HOME/.tmux.conf"
    ln -sf "$CONFIG/.ctags" "$HOME/.ctags"
    ln -sf "$CONFIG/.railsrc" "$HOME/.railsrc"
    ln -sf "$CONFIG/.rspec" "$HOME/.rspec"
    ln -sf "$CONFIG/.vimrc" "$HOME/.vimrc"
}


##################################################################
# Installation
##################################################################

if [ "$1" = "brew" ]; then # install brew
    if [ "$OS" = "Mac" ]; then
        InstallBrew
    else
        echo "Brew is only available in OS X"
        Usage
    fi

elif [ "$1" = "vim" ]; then # install vim
    if [ "$OS" = "Mac" ]; then
        InstallMacVim
    elif [ "$OS" = "Linux" ]; then
        InstallLinuxVim
    else
        Usage
    fi

elif [ "$1" = "zsh" ]; then # install oh-my-zsh
    if [ "$OS" = "Mac" ]; then
        thenMacZsh
        InstallZsh
    elif [ "$OS" = "Linux" ]; then
        LinuxZsh
        InstallZsh
    else
        Usage
    fi

elif [ "$1" = "powerline" ]; then # install Powerline
    if [ "$OS" = "Mac" ]; then
        InstallPythonMac
        InstallPowerline
    elif [ "$OS" = "Linux" ]; then
        InstallPythonLinux
        InstallPowerline
    else
        Usage
    fi

elif [ "$1" = "tmux" ]; then # install tmux
    if [ "$OS" = "Mac" ]; then
        InstallTmuxMac
    elif [ "$OS" = "Linux" ]; then
        InstallTmuxLinux
    else
        Usage
    fi

elif [ "$1" = "link" ]; then # Link all dotfiles
    LinkFiles

else
  Usage

fi

