#!/bin/sh

# Helper functions

#
#
#
# Usage
##

Usage() {
  echo "usage: ./install [config] [OS]"
  echo
  echo "config:"
  echo "    brew (OS X only)"
  echo "    vim"
  echo "    zsh"
  echo "    powerline"
  echo "    tmux"
  echo
  echo "OS:"
  echo "    --mac"
  echo "    --linux"
  echo
}

#
#
#
# Brew
##

InstallBrew() {
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

#
#
#
# Vim
##

InstallMacVim() {
  brew install vim --with-lua
}

InstallLinuxVim() {
  sudo apt-get remove --purge vim vim-runtime vim-gnome vim-tiny vim-common vim-gui-common
  sudo apt-get install liblua5.1-dev luajit libluajit-5.1 python-dev ruby-dev libperl-dev mercurial libncurses5-dev libgnome2-dev libgnomeui-dev libgtk2.0-dev libatk1.0-dev libbonoboui2-dev libcairo2-dev libx11-dev libxpm-dev libxt-dev
  sudo mkdir /usr/include/lua5.1/include
  sudo ln -s /usr/include/luajit-2.0 /usr/include/lua5.1/include
   
  cd ~
  git clone https://github.com/vim/vim.git
  cd vim/src
  make distclean
  ./configure --with-features=huge \
              --enable-rubyinterp \
              --enable-largefile \
              --disable-netbeans \
              --enable-pythoninterp \
              --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu \
              --enable-perlinterp \
              --enable-luainterp \
              --with-luajit \
              --enable-gui=auto \
              --enable-fail-if-missing \
              --with-lua-prefix=/usr/include/lua5.1 \
              --enable-cscope 
  make 

  sudo make install

  cd ..
  sudo mkdir /usr/share/vim
  sudo mkdir /usr/share/vim/vim74
  sudo cp -fr runtime/* /usr/share/vim/vim74/
}

InstallVimConfig() {
  curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh > install.sh
  chmod 755 install.sh
  ./install.sh
  rm install.sh
  git clone git@github.com:darwin67/_vim.git
  mv _vim ~
  mv ~/_vim ~/.vim
  cp ~/.vim/.vimrc ~
}

#
#
#
# Zsh
##

SetZsh() {
  zsh --version
  chsh -s $(which zsh)
}

MacZsh() {
  brew install zsh
  SetZsh
}

LinuxZsh() {
  sudo apt-get install zsh
  SetZsh
}

InstallZsh() {
  sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
}


#
#
#
# Powerline
##

CheckPyVersion() {
  python --version
  pip --version
}

InstallPythonMac() {
  brew install python
  CheckPyVersion
}

InstallPythonLinux() {
  sudo apt-get -y install python
  sudo apt-get -y install python-pip
  CheckPyVersion
}

InstallPowerline() {
  pip install --user powerline-status
  ls ~/Library/Python/2.7/lib/python/site-packages/powerline
  cd ~/Desktop
  git clone git@github.com:powerline/fonts.git
  cd fonts
  ./install.sh

  echo "*************************************************************"
  echo "Please set font to 'Meslo LG S for Powerline'"
  echo "*************************************************************"

  echo "Adding path to .zshrc"
}

AppendPLPathMac() {
  echo "export PATH=\"\$HOME/Library/Python/2.7/bin:\$PATH\"" >> ~/.zshrc
  echo "powerline-daemon -q" >> ~/.zshrc
}

AppendPLPathLinux() {
  echo "export PATH=\"$HOME/.local/bin:$PATH\"" >> ~/.zshrc
  echo "powerline-daemon -q" >> ~/.zshrc
}

#
#
#
# Tmux
#

InstallTmuxMac() {
  brew install tmux
}

InstallTmuxLinux() {
  sudo apt-get install tmux
}

InstallTmuxConfig() {
  cd ~
  git clone git@github.com:darwin67/_dotfiles.git
  mv dotfiles .dotfiles
  cp .dotfiles/.tmux.conf ~
  mkdir ~/.tmux
  cd ~/.tmux
  git clone git@github.com:darwin67/tmux-powerline.git
  echo "See https://github.com/darwin67/dotfiles for details to add things to your .zshrc file"
}

#
#
#
# Helper functions
#
MacOrLinux() {
  if [ "$2" = "--mac" ]; then
    $3
  elif [ "$2" = "--linux" ]; then
    $4
  fi
}


#
#
#
# Installation
#
if [ "$1" = "brew" ]; then # install brew
  if [ ! -z "$2" ]; then
    MacOrLinux $1 $2 InstallBrew Usage
  else
    Usage
  fi

elif [ "$1" = "vim" ]; then # install vim
  if [ ! -z "$2" ]; then
    MacOrLinux $1 $2 InstallMacVim InstallLinuxVim
    InstallVimConfig
  else
    Usage
  fi

elif [ "$1" = "zsh" ]; then # install oh-my-zsh
  if [ ! -z "$2" ]; then
    MacOrLinux $1 $2 MacZsh LinuxZsh
    InstallZsh
  else
    Usage
  fi

elif [ "$1" = "powerline" ]; then # install Powerline
  if [ ! -z "$2" ]; then
    MacOrLinux $1 $2 InstallPythonMac InstallPythonLinux
    InstallPowerline
    MacOrLinux $1 $2 AppendPLPathMac AppendPLPathLinux
  else
    Usage
  fi

elif [ "$1" = "tmux" ]; then # install tmux
  if [ ! -z "$2" ]; then
    MacOrLinux $1 $2 InstallTmuxMac InstallTmuxLinux
    InstallTmuxConfig
  else
    Usage
  fi

else
  Usage

fi

