#!/bin/bash

files=(.zshrc .zlogin .ctags .railsrc .spacemacs .irbrc .pryrc .gitconfig .gitignore_global .tmux.conf)

for file in ${files[@]}; do
    ln -sf "${PWD}/${file}" "${HOME}/${file}"
done

mkdir -p "${HOME}/.config/nvim"
ln -sf "${PWD}/init.vim" "${HOME}/.config/nvim/init.vim"

ln -sf "${PWD}/install" "${HOME}/bin/setup"
