#!/bin/bash

RUBY_PKG='rubocop sqlint mdl rails pry awesome_print neovim bundler pry-byebug pry-doc solargraph'
NODE_PKG='js-beautify eslint typescript tslint typescript-formatter typescript-language-server dockerfile_lint neovim yarn bash-language-server pyright'
PYTHON_PKG="awscli neovim jedi flake8 importmagic pytest autoflake isort yapf python-language-server importmagic epc ipython pipenv"

WHICH=${1:-all}

function install_ruby() {
    echo "Installing ruby dependencies..."
    gem install $RUBY_PKG
}

function install_python() {
    echo "Installing Python dependencies..."
    pip install $PYTHON_PKG
}

function install_node() {
    echo "Installing Node dependencies..."
    npm i -g $NODE_PKG
}

function install_golang() {
    go install github.com/cjbassi/gotop@latest
    go install github.com/mdempsky/gocode@latest
    # go install github.com/rogpeppe/godef@latest
    go install golang.org/x/tools/cmd/guru@latest
    go install github.com/x-motemen/gore/cmd/gore@latest
    # go install golang.org/x/tools/cmd/goimports@latest
    # go install golang.org/x/tools/cmd/godoc@latest
    # go install github.com/zmb3/gogetdoc@latest
    go get -u github.com/cweill/gotests/...
    # go install github.com/haya14busa/gopkgs/cmd/gopkgs@latest
    # go install github.com/davidrjenni/reftools/cmd/fillstruct@latest
    # go install github.com/josharian/impl@latest
    # go install github.com/alecthomas/gometalinter@latest
    # go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    # go install github.com/godoctor/godoctor@latest
    go install github.com/fatih/gomodifytags@latest
    go install golang.org/x/tools/gopls@latest
}

if [[ ${WHICH} == 'all' ]]; then
  install_ruby
  install_python
  install_node
  install_golang
else
  eval install_${WHICH}
fi
