#!/usr/bin/bash

WOBSOCK="$XDG_RUNTIME_DIR/wob.sock"

pactl set-sink-volume @DEFAULT_SINK@ 100% &&
  pactl get-sink-volume @DEFAULT_SINK@ | head -n 1 | awk '{print substr($5, 1, length($5)-1)}' >$WOBSOCK
