#!/usr/bin/bash

WOBSOCK="$XDG_RUNTIME_DIR/wob.sock"

pactl set-source-volume @DEFAULT_SOURCE@ 100% &&
  pactl get-source-volume @DEFAULT_SOURCE@ | head -n 1 | awk '{print substr($5, 1, length($5)-1)}' >$WOBSOCK
