#!/usr/bin/zsh

RUBY_PKG='rubocop sqlint mdl rails pry awesome_print neovim bundler pry-byebug pry-doc solargraph'
NODE_PKG='js-beautify eslint typescript tslint typescript-formatter typescript-language-server dockerfile_lint neovim yarn bash-language-server pyright'
PYTHON_PKG="awscli neovim jedi flake8 importmagic pytest autoflake isort yapf python-language-server importmagic epc ipython pipenv nose"

WHICH=${1:-all}

function install_ruby() {
    echo "Installing ruby dependencies..."
    gem install $RUBY_PKG
}

function install_python() {
    echo "Installing Python dependencies..."
    pip install $PYTHON_PKG
}

function install_node() {
    echo "Installing Node dependencies..."
    npm i -g $NODE_PKG
}

if [[ ${WHICH} == 'all' ]]; then
  install_ruby
  install_python
  install_node
else
  eval install_${WHICH}
fi
