# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Bootloader.
  boot.loader = {
    grub = {
      enable = true;
      device = "/dev/nvme0n1";
      useOSProber = true;
      enableCryptodisk = true;
    };
  };

  boot.initrd.luks.devices."luks-8f715e48-de6c-4957-9b57-f2bb95c3fa25".device =
    "/dev/disk/by-uuid/8f715e48-de6c-4957-9b57-f2bb95c3fa25";
  # Setup keyfile
  boot.initrd.secrets = { "/crypto_keyfile.bin" = null; };

  boot.initrd.luks.devices."luks-5ce5a879-78f8-4928-b976-7ad09f3f6144".keyFile =
    "/crypto_keyfile.bin";
  boot.initrd.luks.devices."luks-8f715e48-de6c-4957-9b57-f2bb95c3fa25".keyFile =
    "/crypto_keyfile.bin";

  boot.initrd.luks.devices."luks-5ce5a879-78f8-4928-b976-7ad09f3f6144".device =
    "/dev/disk/by-uuid/5ce5a879-78f8-4928-b976-7ad09f3f6144";

  swapDevices =
    [{ device = "/dev/disk/by-uuid/25e16122-7d05-4197-b098-928f586884a7"; }];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.supportedFilesystems = [ "zfs" ];

  boot.zfs = {
    forceImportRoot = false;
    extraPools = [ "storage" ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/c9248ae4-2104-4ade-adcc-15c3bedf5162";
      fsType = "ext4";
    };

    "/home/darwin/storage" = {
      device = "/mnt/storage";
      fsType = "none";
      options = [ "bind" ];
    };
  };

  networking.hostId = "f5269c92";
  networking.hostName = "nixos-sophie"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp9s0f3u2u1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

}
