- name: Dynamic Wallpaper directory
  file:
    state: directory
    path: ~/Pictures/DynamicWallpapers
    recurse: true

- name: Download Dynamic Wallpapers
  get_url:
    url: "https://cdn.dynamicwallpaper.club/wallpapers/{{ item.src }}"
    dest: "~/Pictures/DynamicWallpapers/{{ item.filename }}"
  loop:
    - src: "a9q1jiy0cu/%22Desert%20Sands%22%20by%20Louis%20Coyle.heic"
      filename: DesertSands.heic
    - src: "f8jzf4ugy8/Mojave%20XP.heic"
      filename: Mojave.heic
    - src: "hqzkn6nai0f/earth%20.heic"
      filename: Earth.heic
    - src: "ze2isquaf7n/Tech%20Factory.heic"
      filename: TechFactory.heic
    - src: "v5y04cx6k9k/Catalina.heic"
      filename: Catalina.heic
    - src: "boc339cw3n/Big%20macOS%20Sur.heic"
      filename: macBigSur.heic
    - src: "la4wfuwtkg/macOS%20Monterey.heic"
      filename: macMonterey.heic
    - src: "gpf7f97jk3b/Fuji.heic"
      filename: Fuji.heic
# - name: Install systemd service for Dynamic Wallpaper
#   become: true
#   template:
#     src: wallutils/systemd.service
#     dest: /usr/lib/systemd/user/dwall.service
#     mode: 0644
#   notify:
#     - Restart Dynamic Wallpapers
#   vars:
#     theme: macBigSur

# - name: Start and enable Dynamic Wallpaper service
#   systemd:
#     name: dwall
#     scope: user
#     state: started
#     enabled: true
