#!/usr/local/bin/zsh
#
# ================================================================================
#   Functions
# ================================================================================

function weather() {
    local LOCATION="SanFrancisco"
    if [ $1 ]; then
	LOCATION="$1"
    fi
    eval 'curl -sS wttr.in/'$LOCATION
}


function link_config_files() {
    ln -sf $CONFIG/.zlogin $HOME/.zlogin
    ln -sf $CONFIG/.zpreztorc $HOME/.zpreztorc
    ln -sf $CONFIG/.zshrc $HOME/.zshrc
    ln -sf $CONFIG/.sqliterc $HOME/.sqliterc
    ln -sf $CONFIG/.ctags $HOME/.ctags
    ln -sf $CONFIG/.railsrc $HOME/.railsrc
    ln -sf $CONFIG/.rspec $HOME/.rspec
    ln -sf $CONFIG/.spacemacs $HOME/.spacemacs
    ln -sf $CONFIG/.irbrc $HOME/.irbrc
    ln -sf $CONFIG/.pryrc $HOME/.pryrc
    ln -sf $CONFIG/.gemrc $HOME/.gemrc
    ln -sf $CONFIG/.rubocop.yml $HOME/.rubocop.yml
    ln -sf $CONFIG/.gitconfig $HOME/.gitconfig
    ln -sf $CONFIG/.gitignore_global $HOME/.gitignore_global

    case "$OS" in
        Mac)
            ln -sf $CONFIG/.tmux-osx.conf $HOME/.tmux.conf
            ;;
        Linux)
            ln -sf $CONFIG/.tmux-linux.conf $HOME/.tmux.conf
            ;;
    esac

    if [[ -d $HOME/.zprezto/modules/prompt/functions ]]; then
        ln -sf $CONFIG/custom/themes/prompt_custom_setup $HOME/.zprezto/modules/prompt/functions/prompt_custom_setup
    fi
}


function install_powerline_fonts() {
    mkdir -p $HOME/workspace/tmp && cd $HOME/workspace/tmp &&\
        git clone git@github.com:powerline/fonts.git && \
        fonts/install.sh

    echo "*************************************************************"
    echo "Please set font to 'Meslo LG S for Powerline'"
    echo "*************************************************************"
}
