#!/usr/local/bin/zsh
#
# ================================================================================
#   Linux specific configs
# ================================================================================

export PATH="/usr/games:$PATH"
export PATH="/usr/local/games:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export TERM="xterm-256color"