#!/usr/local/bin/zsh
#
# ================================================================================
#   Powerline Configuration
# ================================================================================

if ! type tmux > /dev/null 2>&1; then
    case "OS" in
        Mac)
            brew install tmux
            ;;
        Linux)
            sudo apt install tmux
            ;;
    esac
fi

export PS1="$PS1"'$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")'
