#!/usr/local/bin/zsh
#
# ================================================================================
#   version controls
# ================================================================================
#

function init_rbenv()  { eval "$(rbenv init -)" }
function init_pyenv()  { eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)" }
function init_goenv()  { eval "$(goenv init -)" }
function init_nodenv() { eval "$(nodenv init -)" }

# Ruby
export RBENV_ROOT="$HOME/.rbenv"
export PATH="$RBENV_ROOT/shims:$RBENV_ROOT/bin:$PATH"
if [[ ! -d "$RBENV_ROOT" ]]; then
    git clone git@github.com:rbenv/rbenv.git $RBENV_ROOT && \
        git clone git@github.com:rbenv/ruby-build.git $RBENV_ROOT/plugins/ruby-build && \
        git clone git@github.com:rkh/rbenv-update.git $RBENV_ROOT/plugins/rbenv-update
fi

# Python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"
if [[ ! -d $PYENV_ROOT ]]; then
    git clone git@github.com:yyuu/pyenv.git $PYENV_ROOT && \
        git clone git@github.com:yyuu/pyenv-update.git $PYENV_ROOT/plugins/pyenv-update && \
        git clone git@github.com:yyuu/pyenv-virtualenv.git $PYENV_ROOT/plugins/pyenv-virtualenv
fi

# Go
export GOENV_ROOT="$HOME/.goenv"
export PATH="$GOENV_ROOT/shims:$GOENV_ROOT/bin:$PATH"
if [[ ! -d $GOENV_ROOT ]]; then
    git clone git@github.com:kaneshin/goenv.git $GOENV_ROOT
fi

export GOPATH="$HOME/workspace/go-projects"
export GOROOT="/usr/local/go"
export PATH="$GOPATH/bin:$PATH"
if [[ ! -d $GOPATH ]]; then
    mkdir -p $GOPATH
fi

# Node
export NODENV_ROOT="$HOME/.nodenv"
export PATH="$NODENV_ROOT/shims:$NODENV_ROOT/bin:$PATH"
if [[ ! -d $NODENV_ROOT ]]; then
    git clone https://github.com/nodenv/nodenv.git $NODENV_ROOT && \
        git clone https://github.com/nodenv/node-build.git $NODENV_ROOT/plugins/node-build && \
        git clone https://github.com/nodenv/nodenv-update.git $NODENV_ROOT/plugins/nodenv-update && \
        cd ~/.nodenv && src/configure && make -C src && cd
fi
