#!/usr/bin/env bash
#

GITPATH=~/Pictures/nixos-artwork
DEST=/usr/share/backgrounds/nixos

sudo -v

if [[ ! -d $GITPATH ]]; then
    git clone https://github.com/NixOS/nixos-artwork.git $GITPATH
fi

pushd $GITPATH
git pull
popd

sudo mkdir -p $DEST
sudo cp $GITPATH/wallpapers/*.{png,svg} $DEST
