- name: Reload user systemd
  systemd:
    scope: user
    daemon_reload: true

- name: Restart Dynamic Wallpapers
  systemd:
    name: dwall
    scope: user
    state: restarted
    daemon_reload: true
