{ config, lib, pkgs, ... }:

{
  imports = [
    ../../common/linux/conf.nix
    ../../common/linux/pkg.nix
    ./hardware-configuration.nix

    # Work related
    ../../modules/vanta/module.nix
  ];

  sops = {
    defaultSopsFile = ./secrets.enc.yaml;
    defaultSopsFormat = "yaml";
    age.keyFile = "/home/darwin/.config/sops/age/keys.txt";

    secrets.vanta-key = { };
    secrets.vanta-email = { };

    templates = {
      "vanta.conf" = {
        content = ''
          {
            "AGENT_KEY": "${config.sops.placeholder.vanta-key}",
            "OWNER_EMAIL": "${config.sops.placeholder.vanta-email}",
            "NEEDS_OWNER": true
          }
        '';
      };
    };
  };

  environment.systemPackages = with pkgs; [
    slack
    zoom-us
    xdg-desktop-portal
    xdg-desktop-portal-kde
    insomnia

    tailscale
  ];

  services = {
    tailscale = { enable = true; };

    vanta = {
      enable = true;
      configFile = config.sops.templates."vanta.conf".path;
    };
  };

  # Docker related tweaks
  networking = {
    firewall = {
      # No way to apply the interface configuration to all interfaces
      # generated by docker-compose
      enable = true;

      # required to make sure host.docker.internal works
      interfaces = {
        "docker0" = {
          allowedTCPPortRanges = [{
            from = 3000;
            to = 65535;
          }];
        };
        # NOTE: the local bridge interface name
        # `ip link show`
        "br-676bcf9c1def" = {
          allowedTCPPortRanges = [{
            from = 3000;
            to = 65535;
          }];
        };
      };
    };
  };
}
